GET http://localhost:5050/vans

###

GET http://localhost:5050/vans/64c4af96bdcf57cdb5258eb7

###


GET http://localhost:5050/users


###

GET http://localhost:5050/users/64c4af96bdcf57cdb5258eb6


###


POST http://localhost:5050/users
Content-Type: application/json

{}

### 
GET http://localhost:5050/signup


###
POST http://localhost:5050/signup
Content-Type: application/json

{
  "email":"a@a.com",
  "confirmEmail": "a@a.com",
  "password":"p123",
  "confirmPassword":"p123",
  "dateOfBirth": "2023-08-03"
}


###
GET http://localhost:5050/login


###
POST http://localhost:5050/login
Content-Type: application/json

{
  "email":"a@b.com",
  "password":"p123"
}

###

GET http://localhost:5050/host/vans


{
  "_id":"64d713ebb8e2c2a3e9dddbf8"
}

###

POST http://localhost:5050/host/vans
Content-Type: application/json

{
  "_id":"64d713ebb8e2c2a3e9dddbf8"
}
